<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TradingSystem.Domain\TradingSystem.Domain.csproj" />
    <ProjectReference Include="..\TradingSystem.ML\TradingSystem.ML.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
