using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TradingSystem.Application.Abstractions.Market;
using TradingSystem.Application.DTOs;
using TradingSystem.ML.Abstractions;
using TradingSystem.ML.Services;

namespace TradingSystem.Application.Services
{
    public class MarketQueryService
    {
        private readonly IMLPredictor _mLPredictor;
        private readonly IPredictionService _predictionService;
        private readonly ISymbolRepository _symbolRepository;
        //private readonly Services.IMarketDataService _marketDataService;
        //private readonly TradingSystem.Infrastructure.Messaging.IRabbitMqService _mq;
        //private readonly TradingSystem.Api.Clients.IMarketCollectorClient? _collectorClient;

        public MarketQueryService(IMLPredictor mLPredictor, IPredictionService predictionService, ISymbolRepository symbolRepository)
        {
            _mLPredictor = mLPredictor;
            _predictionService = predictionService;
            _symbolRepository = symbolRepository;
        }

        public async Task<IEnumerable<InstrumentDto>> GetInstrumentsAsync(CancellationToken ct = default)
        {
            throw new NotImplementedException();
            //var instruments = await _marketDataService.GetAllInstrumentsAsync();
            //return instruments.Select(i => new InstrumentDto
            //{
            //    InstrumentId = i.Id,
            //    Symbol = i.Symbol,
            //    Name = i.Name,
            //    Exchange = i.Exchange,
            //    Currency = i.Currency
            //});
        }

        public async Task<CandleDto> GetLatestAsync(string symbol, CancellationToken cancellationToken = default)
        {
            throw new NotImplementedException();
            //var inst = await _marketDataService.GetInstrumentBySymbolAsync(symbol);
            //if (inst == null) return null;

            //var latest = await _marketDataService.GetLatestAsync(inst.Id, TradingSystem.Domain.Enums.AggregationInterval.OneMinute);
            //if (latest == null) return null;

            //return new CandleDto
            //{
            //    InstrumentId = latest.InstrumentId,
            //    Symbol = symbol,
            //    Timestamp = latest.Timestamp,
            //    Open = latest.Open,
            //    High = latest.High,
            //    Low = latest.Low,
            //    Close = latest.Close,
            //    Volume = latest.Volume,
            //    Interval = latest.Interval.ToString()
            //};
        }

        public async Task<IEnumerable<CandleDto>> GetHistoryAsync(string symbol, DateTime from, DateTime to, string interval, CancellationToken cancellationToken = default)
        {
            throw new NotImplementedException();
            //var inst = await _marketDataService.GetInstrumentBySymbolAsync(symbol);
            //if (inst == null) return Enumerable.Empty<CandleDto>();

            //if (!Enum.TryParse<Domain.Enums.AggregationInterval>(interval, true, out var agg))
            //{
            //    agg = Domain.Enums.AggregationInterval.OneMinute;
            //}

            //var data = await _marketDataService.GetHistoryAsync(inst.Id, from, to, agg);
            //return data.Select(d => new CandleDto
            //{
            //    InstrumentId = d.InstrumentId,
            //    Symbol = symbol,
            //    Timestamp = d.Timestamp,
            //    Open = d.Open,
            //    High = d.High,
            //    Low = d.Low,
            //    Close = d.Close,
            //    Volume = d.Volume,
            //    Interval = d.Interval.ToString()
            //});
        }

        public async Task<PredictionDto> GetPredictionAsync(string symbol, CancellationToken ct = default)
        {
            var result = await _predictionService.PredictAsync(symbol, ct);

            return new PredictionDto
            {
                Symbol = symbol,
                ProbabilityUp = result.ProbabilityUp,
                ModelVersion = result.ModelVersion,
                Note = "Prediction generated by ML model"
            };
        }

        public async Task TriggerCollectAsync(TriggerRequest req, CancellationToken ct = default)
        {
            throw new NotImplementedException();
            // 1) سعی کن از Refit client استفاده کنی اگر پیکربندی شده
            //if (_collectorClient is not null)
            //{
            //    try
            //    {
            //        await _collectorClient.TriggerCollectAsync(req);
            //        return;
            //    }
            //    catch
            //    {
            //        // fallback to RabbitMQ publish
            //    }
            //}

            //// 2) fallback: publish a message to RabbitMQ
            //await _mq.PublishAsync("collector.trigger", req);
        }

        public Task<SymbolDto> GetSymbolInfoAsync(string symbol, CancellationToken ct = default)
         => _symbolRepository.GetSymbolAsync(symbol, ct);
    }
}
